# Generated by Django 3.2.7 on 2021-12-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table=None,
        ),
    ]
