# Generated by Django 3.2.7 on 2021-12-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0003_auto_20211221_1559'),
        ('USERAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
