# Generated by Django 3.2.7 on 2021-12-22 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USERAPP', '0002_delete_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressCity', models.CharField(max_length=100, verbose_name='Şehir')),
                ('addressText', models.TextField(max_length=1000, verbose_name='Adres Detayı')),
                ('addressTitle', models.CharField(max_length=50, verbose_name='Adres Başlığı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
        ),
    ]
