# Generated by Django 3.2.7 on 2021-12-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0002_auto_20211223_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='auth_user',
        ),
    ]
