# Generated by Django 3.2.7 on 2021-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0009_alter_customusermodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
