# Generated by Django 3.2.7 on 2021-12-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0013_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='Cart',
        ),
    ]
