# Generated by Django 3.2.7 on 2021-12-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0014_alter_cartmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressmodel',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='favoritemodel',
            table='Favorites',
        ),
    ]
