# Generated by Django 3.2.7 on 2022-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0016_auto_20211227_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
    ]
