# Generated by Django 3.2.7 on 2021-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategorieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorieTitle', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=50, verbose_name='Ürün İsmi')),
                ('productPrice', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('productDescription', models.TextField(max_length=500, verbose_name='Ürün Açıklaması')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Ürün Görseli')),
                ('productShipping', models.BooleanField(default=False, verbose_name='Ücretsiz Kargo Mu')),
                ('productCategorie', models.ManyToManyField(to='PRODUCTS.ProductCategorieModel', verbose_name='Kategori')),
            ],
        ),
    ]
