# Generated by Django 3.2.7 on 2021-12-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0001_initial'),
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Ürün Görseli'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Adet')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERAPP.customermodel', verbose_name='Müşteri')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PRODUCTS.productmodel', verbose_name='Ürün')),
            ],
        ),
    ]
