# Generated by Django 3.2.7 on 2022-01-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoriemodel',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli'),
        ),
        migrations.CreateModel(
            name='ProductCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('commentText', models.TextField(default=None, max_length=250, verbose_name='Yorum')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri İsmi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PRODUCTS.productmodel', verbose_name='Ürün adı')),
            ],
            options={
                'verbose_name_plural': 'Ürün Yorumları',
                'db_table': 'Comments',
            },
        ),
    ]
