# Generated by Django 3.2.7 on 2021-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0002_auto_20211224_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentsmodel',
            name='commentText',
            field=models.TextField(default=None, max_length=250, verbose_name='Yorum'),
        ),
    ]
