# Generated by Django 3.2.7 on 2022-01-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0002_auto_20220120_1816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategoriemodel',
            table='Product_Categorie',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='Products',
        ),
    ]
