# Generated by Django 3.2.7 on 2021-12-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCTS', '0003_productcommentsmodel_commenttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentsmodel',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri İsmi'),
        ),
    ]
