# Generated by Django 3.2.7 on 2022-01-20 15:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0004_productmodel_newslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='newSlug',
            field=autoslug.fields.AutoSlugField(auto_created=True, default='', editable=False, populate_from='productTitle', unique=True),
        ),
    ]
