# Generated by Django 3.2.7 on 2021-12-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0004_productcommentsmodel_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategoriemodel',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='productcommentsmodel',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='Products',
        ),
    ]
