# Generated by Django 3.2.7 on 2021-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0004_favoritemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='productShipping',
            field=models.BooleanField(default=False, verbose_name='Ücretsiz Kargo Mu'),
        ),
    ]
