# Generated by Django 3.2.7 on 2021-12-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0005_auto_20211224_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoriemodel',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='productcommentsmodel',
            options={'verbose_name_plural': 'Ürün Yorumları'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Ürünler'},
        ),
    ]
