# Generated by Django 3.2.7 on 2021-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0005_productmodel_productshipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategorieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorieTitle', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productCategorie',
            field=models.ManyToManyField(to='PRODUCTS.ProductCategorieModel', verbose_name='Kategori'),
        ),
    ]
