# Generated by Django 3.2.7 on 2022-01-20 16:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0005_alter_productmodel_newslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='newSlug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='productTitle', unique=True),
        ),
    ]
