# Generated by Django 3.2.7 on 2022-01-24 13:41

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0006_auto_20220120_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoriemodel',
            name='material_icons',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='newSlug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, populate_from='productTitle', unique=True),
        ),
    ]
