# Generated by Django 3.2.7 on 2021-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0006_auto_20211227_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentsmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
