# Generated by Django 3.2.7 on 2021-12-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0003_addressmodel'),
        ('PRODUCTS', '0006_auto_20211221_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderAddress_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERAPP.addressmodel'),
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
