# Generated by Django 3.2.7 on 2022-01-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0007_auto_20220124_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategoriemodel',
            old_name='material_icons',
            new_name='materialIcon',
        ),
    ]
