# Generated by Django 3.2.7 on 2021-12-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0007_auto_20211223_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='orderAddress_id',
        ),
        migrations.DeleteModel(
            name='FavoriteModel',
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
