# Generated by Django 3.2.7 on 2022-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0008_rename_material_icons_productcategoriemodel_materialicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productCategorie',
            field=models.ManyToManyField(related_name='categories', to='PRODUCTS.ProductCategorieModel', verbose_name='Kategori'),
        ),
    ]
