# Generated by Django 3.2.7 on 2021-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0008_alter_productcommentsmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentsmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
