# Generated by Django 3.2.7 on 2022-01-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0011_alter_productcommentsmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.productmodel', verbose_name='Ürün adı'),
        ),
    ]
