# Generated by Django 3.2.7 on 2021-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adet')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name='Tamamlandı mı')),
                ('transaction_id', models.CharField(max_length=200, null=True, verbose_name='İşlem Numarası')),
            ],
        ),
    ]
