# Generated by Django 3.2.7 on 2021-12-22 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUCTS', '0008_auto_20211223_0011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USERAPP', '0004_favoritemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name='Tamamlandı mı')),
                ('transaction_id', models.CharField(max_length=200, null=True, verbose_name='İşlem Numarası')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('orderAddress_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERAPP.addressmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adet')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.ordermodel', verbose_name='Sipariş')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PRODUCTS.productmodel', verbose_name='Ürün')),
            ],
        ),
    ]
