# Generated by Django 3.2.7 on 2021-12-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORDERS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USERAPP', '0001_initial'),
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='orderAddress_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERAPP.addressmodel'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.ordermodel', verbose_name='Sipariş'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PRODUCTS.productmodel', verbose_name='Ürün'),
        ),
    ]
