# Generated by Django 3.2.7 on 2021-12-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitemmodel',
            table='Order_Items',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='Orders',
        ),
    ]
