# Generated by Django 3.2.7 on 2021-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0005_rename_orderaddress_id_ordermodel_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
