# Generated by Django 3.2.7 on 2022-01-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0006_ordermodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ORDERS.ordermodel', verbose_name='Sipariş'),
        ),
    ]
